
eureka:
  instance:
    prefer-ip-address: true
    appname: security-service-A
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  profiles:
    active: dev

