version: '2.2'
services:
  elasticsearch:
    image: elasticsearch:6.4.3
    container_name: es
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
#    volumes:
#      - es1data:/usr/share/elasticsearch/data
#      - es1/log:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
#  elasticsearch2:
#    image: elasticsearch:6.4.3
#    container_name: es2
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - "discovery.zen.ping.unicast.hosts=elasticsearch"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - es2data:/usr/share/elasticsearch/data
#      - es2/log:/usr/share/elasticsearch/logs
#    networks:
#      - esnet
  kibana:
    image: kibana:6.4.3
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - esnet
    environment:
      - SERVER_NAME=kibana
      - XPACK_MONITORING_ENABLED=true
      - ELASTICSEARCH_HOSTS-http://elasticsearch:9200
  logstash:
    image: logstash:6.4.3
    container_name: logstash
    networks:
      - esnet
    ports:
      - 5044:5044
      - 9600:9600
volumes:
  es1data:
    driver: local
#  es1/log:
#    driver: local
  es2data:
    driver: local
#  es2/log:
#    driver: local

networks:
  esnet: