#spring:
##  application:
##    name: dubbo-auto-configure-consumer-sample
##demo:
##  service:
##    version: 1.0.0
##
##dubbo:
##  registry:
##    address: zookeeper:/127.0.0.1:2181
###    file: ${user.home}/dubbo-cache/dubbo-auto-configure-consumer-sample/dubbo.cache
##server:
##  port: 8082