spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
       ddl-auto: update
  datasource:
    platform: MYSQL
    url: jdbc:mysql://localhost:3306/louis_micro_service?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: Root
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: resource-service

  main:
    allow-bean-definition-overriding: true
server:
  port: 9319
logging:
  level:
    org:
      springframework.security: DEBUG

security:
  oauth2:
    resource:
      id: order
      user-info-uri: http://localhost:8981/usa/user
      prefer-token-info: false