
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: MYSQL
    url: jdbc:mysql://localhost:3306/louis_micro_service?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: Root
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: resource-service
  profiles:
    active: dev


  main:
    allow-bean-definition-overriding: true
server:
  port: 8082
logging:
  level:
    org:
      springframework.security: DEBUG

security:
  oauth2:
    resource:
      id: resource
      user-info-uri: http://localhost:8081/uaa/current
      prefer-token-info: false